apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapi-deployment
  labels:
    app: sampleapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapi
  template:
    metadata:
      labels:
        app: sampleapi
    spec:
      containers:
      - name: sampleapi
        image: maaaruf/sampleapi
        ports:
        - containerPort: 80
        - containerPort: 443