apiVersion: v1
kind: Service
metadata:
  name: sampleapi-service
spec:
  type: NodePort
  selector:
    app: sampleapi
  ports:
    - name: http
      protocol: TCP
      port: 801
      targetPort: 80
      nodePort: 30001
